### ISSUE TITLE
Doesn't work with YouTube links...

### ISSUE THREAD

**Issue by FetchLeo** [DV8FromTheWorld/JDA-Player#10]
Hi! 

I'm trying to create a small Discord bot (just to see how it's done), and one of the things I wanted to add was a music player.

I got JDA and JDA-Player set up, but now I've run into a very strange issue. If I try to play a YouTube video, I get the `NullPointerException` stating that a "zero-length or null INFO was returned!" **_However, when I play from Soundcloud, it works perfectly fine._**

Some details:
- I'm running this on a Mac; OS X version 10.11 El Capitan
- Python version 3.5.2; I aliased "python" to "python3" so I get that one
- Java 8
- JDA version 2.2.0_334 and JDA-Player version 0.2.2_16
- Latest youtube-dl, ffmpeg, and ffprobe (all in the right directory)

**EDIT:** Accidentally submitted this before I finished. Stupid trackpad. The rest of it is below.

I haven't tried to run this on Linux, because I don't really feel like copying the JAR files over right now.

How to reproduce (at least for me):
- Use the example JDA-Player code (`Bot.java`)
- Try to play something from YouTube
- You should get an error in the console with the NullPointerException.

I'm not sure what I'm doing wrong here. If code is needed, I can provide it.

Thanks.

**Comment by FetchLeo** [comment]
Pinging @DV8FromTheWorld and @MinnDevelopment in case they don't see this.

**Comment by MinnDevelopment** [comment]
Are you sure you have the correct version of ffmpeg and ffprobe installed and accessible via terminal?
Note: You need the static version for your OS and it needs to be accessible from the working directory of your bot or youtube-dl in specific.
You also need the binary script version of youtube-dl

Does this happen for every youtube link?

**Comment by FetchLeo** [comment]
First off, I'd like to point out that I've only tested this using the `Playlist.getPlaylist()` method. Not sure if I should be using something different for YouTube links.

ffmpeg and ffprobe are both installed and accessible; what would the "correct version" be?

The static versions (I'm guessing those are the files that you download and place into the directory) are there as well and work fine. youtube-dl is also accessible, and I did download the binary version.

And yes, this does happen for every YouTube link. 

Output of `ls` in the root project directory (I confirmed that the program is indeed running from there):

![image](https://cloud.githubusercontent.com/assets/14795831/17651131/d0dfd758-6257-11e6-9d65-db87ce9ed8e9.png)

Not sure what's going on here. 

If it helps, here's some output from the command line (running the different `youtube-dl` commands):

![image](https://cloud.githubusercontent.com/assets/14795831/17651134/f709c308-6257-11e6-97d7-1d1e82bb3f7e.png)

Also, upon further inspection (I created my own `Playlist` class), I noticed that when the `Playlist` class tries to read the data from the process, it thinks that there's nothing; although when I run the command that it would've run, from the command line, it obviously does return data.

Hopefully you can help!

Thanks =)

**Comment by FetchLeo** [comment]
pinging @DV8FromTheWorld in case he knows what I should do

**Comment by freyacodes** [comment]
Do you have ffmpeg and ffprobe in your path?

**Comment by FetchLeo** [comment]
Yes, I do. I don't think that's the problem, though; I can still play music from Soundcloud.

ffmpeg, ffprobe, and youtube-dl are all accessible.

**Comment by freyacodes** [comment]
What happens when you manually run this command?

```
python youtube-dl -x <youtube URL>
```

**Comment by FetchLeo** [comment]
Works just fine.

**Comment by FetchLeo** [comment]
Fixed it, I think. Turns out Youtube video IDs are case-sensitive. I was running all input through `toLowerCase()`. Silly me.
