### ISSUE TITLE
Audio randomly dies and all queued songs stop playing.

### ISSUE THREAD

**Issue by TheEpTic** [DV8FromTheWorld/JDA-Player#14]
I've been having a issue lately where the bot will just stop playing music. Out of nowhere the audio will stop and it won't play any songs until I clear the bot's queue and have it fully close the connection.

I'm running the latest development versions of JDA and JDA-Player. (360 JDA) and (18 JDA-Player)

ffmpeg hasn't been touched for a few moths but I often keep YouTube-dl up to date.

YouTube-dl:
`2016.09.04.1`

ffmpeg:
 `ffmpeg version N-80181-g958bf65-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2016 the FFmpeg developers
built with gcc 5.3.1 (Debian 5.3.1-21) 20160528
configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libwebp --enable-libspeex --enable-libvorbis --enable-libvpx --enable-libfreetype --enable-fontconfig --enable-libxvid --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libtheora --enable-libvo-amrwbenc --enable-gray --enable-libopenjpeg --enable-libopus --enable-libass --enable-gnutls --enable-libvidstab --enable-libsoxr --enable-frei0r --enable-libfribidi --disable-indev=sndio --disable-outdev=sndio --enable-librtmp --enable-libmfx --enable-libzimg --cc=gcc
libavutil      55. 24.100 / 55. 24.100
libavcodec     57. 44.100 / 57. 44.100
libavformat    57. 37.101 / 57. 37.101
libavdevice    57.  0.101 / 57.  0.101
libavfilter     6. 46.100 /  6. 46.100
libswscale      4.  1.100 /  4.  1.100
libswresample   2.  0.101 /  2.  0.101
libpostproc    54.  0.100 / 54.  0.100
`

I'm taking thread dumps along with monitoring the threads myself.
If you're interested in the dumps, let me know on Discord and I'll DM.

Thanks.

**Comment by TheEpTic** [comment]
Update: Looks to be YouTube-dl's issue. Still investigating.

**Comment by TheEpTic** [comment]
Found YouTube-dl is hanging because it's trying to use IPv6. OVH's IPv6 blocks are blocked by YouTube. Gonna try forcing ipv4 and see if that resolves the music issue.

**Comment by MinnDevelopment** [comment]
Should be resolved as of the latest commit. See [d4ab360](https://github.com/DV8FromTheWorld/JDA-Player/commit/d4ab360ad8ed593395dfc20ea48ff4539661c7ed)

**Comment by TheEpTic** [comment]
Looks to be good so far, gonna continue to monitor and close this when it looks to be working as intended!

Thank you guys :>

**Comment by TheEpTic** [comment]
Looks to have fixed it! Thank you guys :)
