### ISSUE TITLE
Playlist.java OVH error

### ISSUE THREAD

**Issue by Grasinga** [DV8FromTheWorld/JDA-Player#16]
I think that if the -4 was added to Playlist.java then it should play on our OVH server.
            Collections.unmodifiableList(Arrays.asList(
                    "python",               //Launch python executor
                    "./youtube-dl",         //youtube-dl program file
                    "-q",                   //quiet. No standard out.
                    "-j",                   //Print JSON
                    "--flat-playlist"       //Get ONLY the urls of the playlist if this is a playlist.
            ));
-4 needs to be in there.

**Comment by MinnDevelopment** [comment]
You can easily add specific flags like `-4` by adding them to the list in Playlist.java:
`Playlist.YOUTUBE_DL_PLAYLIST_ARGS.add("-4");`

**Comment by MinnDevelopment** [comment]
Fixed in [e27496c](https://github.com/DV8FromTheWorld/JDA-Player/commit/e27496cd74cc25a6f3d90e84a3eab77208502a5b)
