### ISSUE TITLE
Unable to use the player on unix

### ISSUE THREAD

**Issue by austinv11** [DV8FromTheWorld/JDA-Player#9]
At the moment on my mac it throws an NPE:

```
java.lang.NullPointerException: The YT-DL playlist process resulted in a null or zero-length INFO!
    at net.dv8tion.jda.player.Playlist.getPlaylist(Playlist.java:71)
```

This is because running youtube-dl through python (i.e. `python ./youtube-dl otherArgs...`) doesn't work, running it directly via `youtube-dl otherArgs...` however works fine.

**Comment by MinnDevelopment** [comment]
That might be caused by the default version of python in Linux. You might have python python3 and python3.5 installed. I suggest making sure that the version returned by `python -v` is 3.5.x

**Comment by austinv11** [comment]
I doubt that because the error message when running `python ./youtube-dl` in the shell is `python: can't open file './youtube-dl': [Errno 2] No such file or directory`.

**Comment by austinv11** [comment]
I only had youtube-dl on the path rather than in the same directory as the project, my bad.
